demo/demo/urls.py
from django.contrib import admin
from django.urls import path
from APP1 import views
urlpatterns = [
    path("",views.index),
    path("admin/", admin.site.urls),
    path("login/",views.login),
    path("index",views.index),
    path("index/<int:num>",views.index),
    path("user",views.user_page),
    path("submit",views.submit),
    path("cart",views.cart),
    path("wallet",views.wallet),
    path("exit",views.exit),
    path("user/set",views.user_set),
    path("test/<int:i>",views.test),
    path("user/<int:uid>",views.show),
    path("qr",views.qr),
    path("img/<str:str>",views.img),
    path('docs', views.docs, name='docs'),
    path("set",views.set)
]

demo/APP1/models.py
from django.db import models

# Create your models here.
class Status(models.TextChoices):
     UNSTARTED = 'u', "Not started yet"
     ONGOING = 'o', "Ongoing"
     FINISHED = 'f', "Finished"
class User(models.Model):

    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    name = models.CharField(verbose_name="用户昵称",max_length=128, unique=True)
    email = models.EmailField(verbose_name="邮箱",null=False)
    sex = models.CharField(verbose_name="性别",max_length=32, choices=gender, default="未知")
    c_time = models.DateTimeField(verbose_name="注册时间",auto_now_add=True)
    avater = models.ImageField(verbose_name="头像",upload_to="img",max_length=255,default="img/my.jpg")
    message = models.CharField(verbose_name="留言",blank=True,max_length=255,default="")
    class Meta:
         verbose_name = "用户信息"
         verbose_name_plural = "用户"
    def __str__(self):
         return self.name
class Goods(models.Model):
    c_time = models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    name=models.CharField(verbose_name="商品名称",max_length=50,blank=False)
    level=models.SmallIntegerField(verbose_name="商品成色",blank=True)
    remark=models.CharField(verbose_name="商品详细",max_length=255,blank=True)
    price=models.DecimalField(verbose_name="商品价格",max_digits=10,decimal_places=2,blank=False)
    sort=models.PositiveSmallIntegerField(verbose_name="商品类别",blank=False)
    count=models.PositiveSmallIntegerField(verbose_name="商品数量",blank=False)
    display=models.BooleanField(verbose_name="已上架",default=False)
    transaction = models.PositiveSmallIntegerField(verbose_name="交易方式",blank=True,null=True)
    sales = models.PositiveSmallIntegerField(verbose_name="商品销量",default=0)
    uid =models.IntegerField(verbose_name="商品卖家",)
    image=models.ImageField(verbose_name="商品图片",upload_to="img",max_length=255)
    class Meta:
         verbose_name = "商品信息"
         verbose_name_plural = "商品信息"
class Passwrd(models.Model):
    c_time = models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    password = models.CharField(verbose_name="用户密码",max_length=255,blank=False)
    uid =models.OneToOneField(User,verbose_name="用户id",on_delete=models.CASCADE,primary_key=True)
    class Meta:
         verbose_name = "密码"
         verbose_name_plural = "密码"
class Goods_message(models.Model):
    c_time=models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    sid=models.IntegerField(verbose_name="商品的id",)
    content=models.CharField(verbose_name="留言内容",max_length=128)
    display=models.BooleanField(verbose_name="是否可见",default=True)
    uid=models.IntegerField(verbose_name="评论的用户id",)
    class Meta:
         verbose_name = "商品留言"
         verbose_name_plural = "商品留言"
class Post_goods(models.Model):
    c_time=models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    displa=models.BooleanField(verbose_name="是否被删除",default=False)
    uid=models.IntegerField(verbose_name="用户id",)
    sid=models.IntegerField(verbose_name="对应商品id",)
    class Meta:
         verbose_name = "用户发布的商品"
         verbose_name_plural = "用户发布的商品"
class Bought_goods(models.Model):
    c_time=models.DateTimeField(verbose_name="修改时间",auto_created=True)
    state=models.PositiveSmallIntegerField(verbose_name="商品当前的状态",default=0)
    uid=models.IntegerField(verbose_name="用户id",)
    sid=models.IntegerField(verbose_name="商品id",)
    quantity=models.IntegerField(verbose_name="商品数量",)
    class Meta:
         verbose_name = "用户已购买商品"
         verbose_name_plural = "用户已购买商品"
class Shopping_cart(models.Model):
    c_time=models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    display=models.BooleanField(verbose_name="商品是否被删除",)
    uid=models.IntegerField(verbose_name="用户id",)
    sid=models.IntegerField(verbose_name="商品id",)
    quantity=models.IntegerField(verbose_name="商品数量",)
    class Meta:
         verbose_name = "用户购物车"
         verbose_name_plural = "用户购物车"

demo/APP1/forms.py
from django import forms

    

    


class UserForm_add(forms.Form):
    adduser=forms.CharField(label="",max_length=128,widget=forms.TextInput(attrs={"placeholder":"用户名"}))
    addpwd=forms.CharField(label="",max_length=256,widget=forms.PasswordInput(attrs={"placeholder":"密码"}))
class UserForm_login(forms.Form):
    loginuser=forms.CharField(label="",max_length=128,widget=forms.TextInput(attrs={"placeholder":"用户名"}))
    loginpwd=forms.CharField(label="",max_length=256,widget=forms.PasswordInput(attrs={"placeholder":"密码"}))






class imgtest(forms.Form):

    img=forms.ImageField(label="img")
class goods(forms.Form):
        sort={
             (1,"电器"),
             (2,"书籍"),
        }
        Goods_name=forms.CharField(label="商品名",max_length=128)
        Goods_level=forms.IntegerField(label="成色")
        Goods_remark=forms.CharField(label="商品描述",max_length=255)
        Goods_price=forms.DecimalField(label="商品价钱",decimal_places=3)
        Goods_sort=forms.ChoiceField (label="商品类别",choices=sort)
        Goods_coumt=forms.IntegerField(label="数量")
        Goods_img=forms.ImageField(label="img")
class userinfo(forms.Form):    
# def __init__(self,*args, **kwargs):
#     super().__init__(*args, **kwargs)
    sort={
            ("male","男"),
            ("female","女"),
            ("未知","保密")
        }

    sex=forms.ChoiceField(label="性别",choices=sort)
    email=forms.EmailField(label="Email")
    message=forms.CharField(label="",max_length=255) 
    img=forms.ImageField(label="img")

demo/APP1/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.http import JsonResponse
from .mypy import login_my
from .mypy import img_test
from .mypy import user_info
from . import forms

from . import models
import os
import pyqrcode
import random
# Create your views here.

def frame(func): 
    def f(request,num=1):
        if request.session.get("info",None):
            session=request.session
            info=session.get("info")
            img=models.User.objects.get(id=session.get("info")["id"]).avater
        else :
            img="/img/my.jpg"
        return func(request,img,num)
    return f



#主页
@frame
def index(request,*args):
    if  request.method=="GET":
        if args[1]<=0:

            return redirect("/index")
        # data=models.Goods.objects.order_by("?")[(args[1]-1)*15:(args[1]-1)*15+15]
        user=models.User.objects.all()
        data=list(models.Goods.objects.all()[(args[1]-1)*15:(args[1]-1)*15+15])
        random.shuffle(data)
        count=range(models.Goods.objects.count()//15+1)
        print(locals())
        return render(request,"index/index.html",locals())
    print(request.POST)
    return redirect("/index")

#登录、注册
def login(request):
    if request.method=="POST":
    #    print(request.POST)
       return login_my.post(request)
    return login_my.get(request)


#个人界面
@frame
def user_page(request,*args):
    if request.session.get("info",None):
        if request.method=="GET":
            return user_info.get(request,*args)
        
        return user_info.post(request,*args)
    else:
        return redirect("login/")
#个人商品界面---------（合并到个人界面）
def user_goods_page(request):
    pass



#上架商品
@frame
def submit(request,*args):
    print(request)
    goods=forms.goods()
    if request.method=="GET":
        if request.session.get("info",None):
            return render(request,"submit/submit.html",locals())
        else:
            return redirect("/login")
    data=forms.goods(request.POST,request.FILES)

    
    if data.is_valid():
        req=data.cleaned_data
        img=req.get("Goods_img")
        img_path=os.path.join("APP1","static","img",img.name)
        with open(img_path,"wb+") as f:
            for chunk in img.chunks():
                f.write(chunk)
        print(req)
        models.Goods.objects.create(name=req.get("Goods_name"),
                                    level=req.get("Goods_level"),
                                    remark=req.get("Goods_remark"),
                                    price=req.get("Goods_price"),
                                    sort=req.get("Goods_sort"),
                                    count=req.get("Goods_coumt"),
                                    image=os.path.join("img",img.name),
                                    uid=request.session.get("info").get("id")
                                    )
    return redirect("/user")

#购物车页面
@frame
def cart(request,*args):
    if request.session.get("info",None):
        if request.method=="GET":
            cart=models.Shopping_cart.objects.filter(uid=request.session.get("info")["id"])
            data=[]
            suser=[]
            for i in cart:
                goods=models.Goods.objects.get(id=i.sid)
                data.append({
                    "id":goods.id,
                    "name":goods.name,
                    "price":goods.price,
                    "img":goods.image,
                    "count":goods.count,    
                    "display":goods.display,
                    "seller_id":goods.uid
                    })
                scr={
                    "seller_id":goods.uid,
                    "uname":models.User.objects.get(id=goods.uid).name,
                    "avater":models.User.objects.get(id=goods.uid).avater,
                }
                if scr not in suser :
                    suser.append(scr) 
        
            print(data)
            return render(request,"cart/cart.html",locals())
        print(request.POST)
        models.Shopping_cart.objects.create(
            display=True,
            uid=request.session.get("info")["id"],
            sid=request.POST.get("Goods"),
            quantity=1
        )
        return redirect("/cart")
    else:
            return redirect("/login")
#搜索展示
def searching_goods(request):
    pass
@frame
def wallet(request,*args):
    if request.session.get("info",None):
        return render(request,"wallet/wallet.html",locals())
    return redirect("/login")
def exit(req):
    req.session.flush()
    return redirect("/index")

def user_set(request):
    set=models.Goods.objects.filter(id=request.POST.get("Goods"))
    set.update(display=not set[0].display)
    return redirect("/user")

def show(request,uid):
    user=models.User.objects.get(id=uid)
    data=models.Goods.objects.filter(uid=uid)
    args=(user.avater,)
    print(locals())
    return render(request,"user/other.html",locals())
def test(request,i):
    data=models.Shopping_cart.objects.filter(uid=request.session.get("info")["id"])
    if i==0:
        data.first().delete()
    elif i==1:
        data.delete()
    return redirect("/cart")
@frame
def qr(req,*args):
    if req.session.get("info",None):
        url=req.get_host()+"/user/"+str(req.session.get("info")["id"])
        url=pyqrcode.create(url,version=5)
        qr_path=os.path.join("APP1","static","qr",str(req.session.get("info")["id"])+".svg")
        print(url.terminal(quiet_zone=1))
  
        url.svg(qr_path,scale=8)
        qr=os.path.join("qr",str(req.session.get("info")["id"])+".svg")
        print(locals())
        return render(req,"QR/qr.html",locals())
    return redirect("/login")
def img(req,str):
    return redirect("/static/img/"+str)
@frame
def set(req,*args):

    if req.method=="GET":
        uid=req.session.get("info").get("id")
        user=models.User.objects.get(id=uid)
        data=models.Goods.objects.filter(uid=uid)
        form_data = {
        "sex":user.sex,
        "email": user.email,
        "message":  user.message if user.message else "说点什么吧...",
        "img":user.avater
        }
        formuser=forms.userinfo(form_data)
        print(locals())
        return render(req,"set_user/set_user.html",locals())
    data=forms.userinfo(req.POST,req.FILES)
    print(data.changed_data)
    if data.is_valid():
        user=models.User.objects.filter(id=req.session.get("info").get("id"))
        if data.cleaned_data.get("message")!="说点什么吧...":
            user.update(message=data.cleaned_data.get("message"))
        if data.cleaned_data.get("email")!=user.values()[0].get("email"):
            user.update(email=data.cleaned_data.get("email"))
        if data.cleaned_data.get("sex")!=user.values()[0].get("sex"):
            user.update(sex=data.cleaned_data.get("sex")) 
        print(data.cleaned_data)
        if data.cleaned_data.get("img")!=user.values()[0].get("img"):
            req=data.cleaned_data
            img=req.get("img")
            img_path=os.path.join("APP1","static","img",img.name)
            with open(img_path,"wb+") as f:
                for chunk in img.chunks():
                    f.write(chunk)
            user.update(avater=os.path.join("img",img.name))
    
    return redirect("/user")

def docs(request):
    return render(request, 'help/help_user.html')

demo/APP1/templates/submit/submit.html
{% extends 'frame.html' %}
{% load static %}

{% block main %}



<style>
  form {
    max-width: 780px;
    margin: auto;
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 5px;
  }

  label {
    font-weight: bold;
  }

  input[type="text"],
  input[type="number"],
  textarea {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;
    border: none;
    border-radius: 4px;
    background-color: #fff;
  }

  input[type="submit"] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type="submit"]:hover {
    background-color: #45a049;
  }

  .button {
    width: 150px;
    background-color: #5995fd;
    border: none;
    outline: none;
    height: 49px;
    border-radius: 49px;
    color: #fff;
    text-transform: uppercase;
    font-weight: 600;
    margin: 10px 0;
    cursor: pointer;
    transition: 0.5s;
  }

  .custum-file-upload {
    height: 200px;
    width: 300px;
    display: flex;
    flex-direction: column;
    align-items: space-between;
    gap: 20px;
    cursor: pointer;
    align-items: center;
    justify-content: center;
    border: 2px dashed #cacaca;
    background-color: rgba(255, 255, 255, 1);
    /* padding: 1.5rem; */
    border-radius: 10px;
    box-shadow: 0px 48px 35px -48px rgba(0, 0, 0, 0.1);
  }

  .custum-file-upload .icon {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .custum-file-upload .icon svg {
    height: 80px;
    fill: rgba(75, 85, 99, 1);
  }

  .custum-file-upload .text {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .custum-file-upload .text span {
    font-weight: 400;
    color: rgba(75, 85, 99, 1);
  }

  .custum-file-upload input {
    display: none;
  }

  select {
    background-color: #ffffff;
    color: #333;
    border: none;
    padding: 8px;
    font-size: 16px;
  }

  select::-ms-expand {
    display: none;
  }

  select::after {
    content: '\25BC';
    position: absolute;
    top: 50%;
    right: 10px;
    transform: translateY(-50%);
    pointer-events: none;
  }

  .input {
    max-width: 190px;
    height: 44px;
    background-color: #05060f0a;
    border-radius: .5rem;
    padding: 0 1rem;
    border: 2px solid transparent;
    font-size: 1rem;
    transition: border-color .3s cubic-bezier(.25, .01, .25, 1) 0s, color .3s cubic-bezier(.25, .01, .25, 1) 0s, background .2s cubic-bezier(.25, .01, .25, 1) 0s;
  }

  .label {
    display: block;
    margin-bottom: .3rem;
    font-size: .9rem;
    font-weight: bold;
    color: #05060f99;
    transition: color .3s cubic-bezier(.25, .01, .25, 1) 0s;
  }

  .input:hover,
  .input:focus,
  .input-group:hover .input {
    outline: none;
    border-color: #05060f;
  }

  .input-group:hover .label,
  .input:focus {
    color: #05060fc2;
  }
</style>




<form action="/submit" method="post" enctype="multipart/form-data" style="width: 720px;">
  {% csrf_token %}

  {% for i in goods%}
  {%if forloop.counter != 7 %}
  <div class="input-group">
    <label class="label">{{i.label}}</label>
    {{i}}
  </div>
  {% endif %}
  {% endfor %}


  <label class="custum-file-upload" for="id_Goods_img">
    <div class="icon" id="show_img">
      <svg id="svg" xmlns="http://www.w3.org/2000/svg" fill="" viewBox="0 0 24 24">
        <g stroke-width="0" id="SVGRepo_bgCarrier"></g>
        <g stroke-linejoin="round" stroke-linecap="round" id="SVGRepo_tracerCarrier"></g>
        <g id="SVGRepo_iconCarrier">
          <path fill=""
            d="M10 1C9.73478 1 9.48043 1.10536 9.29289 1.29289L3.29289 7.29289C3.10536 7.48043 3 7.73478 3 8V20C3 21.6569 4.34315 23 6 23H7C7.55228 23 8 22.5523 8 22C8 21.4477 7.55228 21 7 21H6C5.44772 21 5 20.5523 5 20V9H10C10.5523 9 11 8.55228 11 8V3H18C18.5523 3 19 3.44772 19 4V9C19 9.55228 19.4477 10 20 10C20.5523 10 21 9.55228 21 9V4C21 2.34315 19.6569 1 18 1H10ZM9 7H6.41421L9 4.41421V7ZM14 15.5C14 14.1193 15.1193 13 16.5 13C17.8807 13 19 14.1193 19 15.5V16V17H20C21.1046 17 22 17.8954 22 19C22 20.1046 21.1046 21 20 21H13C11.8954 21 11 20.1046 11 19C11 17.8954 11.8954 17 13 17H14V16V15.5ZM16.5 11C14.142 11 12.2076 12.8136 12.0156 15.122C10.2825 15.5606 9 17.1305 9 19C9 21.2091 10.7909 23 13 23H20C22.2091 23 24 21.2091 24 19C24 17.1305 22.7175 15.5606 20.9844 15.122C20.7924 12.8136 18.858 11 16.5 11Z"
            clip-rule="evenodd" fill-rule="evenodd"></path>
        </g>
      </svg>
    </div>
    <div class="text" id="text">
      <span>点击提交商品图片</span>
    </div>
    {{ goods.Goods_img}}
  </label>

  <button class="button">提交</button>
</form>
<script>
  var getUserPhoto = document.getElementById("id_Goods_img");
  getUserPhoto.onchange = function () {
    var file = this.files;
    console.log(file);
    var reader = new FileReader();
    reader.readAsDataURL(file[0]);
    reader.onload = function () {
      var image = document.createElement("img");
      image.width = "300";
      image.height = "200";
      image.src = reader.result;
      var showPicture = document.getElementById("show_img");
      var svg = document.getElementById("svg");
      var text = document.getElementById("text");
      svg.remove();
      text.remove();
      showPicture.append(image);
    };
  };
</script>
{% endblock %}