demo/demo/urls.py
from django.contrib import admin
from django.urls import path
from APP1 import views
urlpatterns = [
    path("",views.index),
    path("admin/", admin.site.urls),
    path("login/",views.login),
    path("index",views.index),
    path("index/<int:num>",views.index),
    path("user",views.user_page),
    path("submit",views.submit),
    path("cart",views.cart),
    path("wallet",views.wallet),
    path("exit",views.exit),
    path("user/set",views.user_set),
    path("test/<int:i>",views.test),
    path("user/<int:uid>",views.show),
    path("qr",views.qr),
    path("img/<str:str>",views.img),
    path('docs', views.docs, name='docs'),
    path("set",views.set)
]

demo/APP1/models.py
from django.db import models

# Create your models here.
class Status(models.TextChoices):
     UNSTARTED = 'u', "Not started yet"
     ONGOING = 'o', "Ongoing"
     FINISHED = 'f', "Finished"
class User(models.Model):

    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    name = models.CharField(verbose_name="用户昵称",max_length=128, unique=True)
    email = models.EmailField(verbose_name="邮箱",null=False)
    sex = models.CharField(verbose_name="性别",max_length=32, choices=gender, default="未知")
    c_time = models.DateTimeField(verbose_name="注册时间",auto_now_add=True)
    avater = models.ImageField(verbose_name="头像",upload_to="img",max_length=255,default="img/my.jpg")
    message = models.CharField(verbose_name="留言",blank=True,max_length=255,default="")
    class Meta:
         verbose_name = "用户信息"
         verbose_name_plural = "用户"
    def __str__(self):
         return self.name
class Goods(models.Model):
    c_time = models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    name=models.CharField(verbose_name="商品名称",max_length=50,blank=False)
    level=models.SmallIntegerField(verbose_name="商品成色",blank=True)
    remark=models.CharField(verbose_name="商品详细",max_length=255,blank=True)
    price=models.DecimalField(verbose_name="商品价格",max_digits=10,decimal_places=2,blank=False)
    sort=models.PositiveSmallIntegerField(verbose_name="商品类别",blank=False)
    count=models.PositiveSmallIntegerField(verbose_name="商品数量",blank=False)
    display=models.BooleanField(verbose_name="已上架",default=False)
    transaction = models.PositiveSmallIntegerField(verbose_name="交易方式",blank=True,null=True)
    sales = models.PositiveSmallIntegerField(verbose_name="商品销量",default=0)
    uid =models.IntegerField(verbose_name="商品卖家",)
    image=models.ImageField(verbose_name="商品图片",upload_to="img",max_length=255)
    class Meta:
         verbose_name = "商品信息"
         verbose_name_plural = "商品信息"
class Passwrd(models.Model):
    c_time = models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    password = models.CharField(verbose_name="用户密码",max_length=255,blank=False)
    uid =models.OneToOneField(User,verbose_name="用户id",on_delete=models.CASCADE,primary_key=True)
    class Meta:
         verbose_name = "密码"
         verbose_name_plural = "密码"
class Goods_message(models.Model):
    c_time=models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    sid=models.IntegerField(verbose_name="商品的id",)
    content=models.CharField(verbose_name="留言内容",max_length=128)
    display=models.BooleanField(verbose_name="是否可见",default=True)
    uid=models.IntegerField(verbose_name="评论的用户id",)
    class Meta:
         verbose_name = "商品留言"
         verbose_name_plural = "商品留言"
class Post_goods(models.Model):
    c_time=models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    displa=models.BooleanField(verbose_name="是否被删除",default=False)
    uid=models.IntegerField(verbose_name="用户id",)
    sid=models.IntegerField(verbose_name="对应商品id",)
    class Meta:
         verbose_name = "用户发布的商品"
         verbose_name_plural = "用户发布的商品"
class Bought_goods(models.Model):
    c_time=models.DateTimeField(verbose_name="修改时间",auto_created=True)
    state=models.PositiveSmallIntegerField(verbose_name="商品当前的状态",default=0)
    uid=models.IntegerField(verbose_name="用户id",)
    sid=models.IntegerField(verbose_name="商品id",)
    quantity=models.IntegerField(verbose_name="商品数量",)
    class Meta:
         verbose_name = "用户已购买商品"
         verbose_name_plural = "用户已购买商品"
class Shopping_cart(models.Model):
    c_time=models.DateTimeField(verbose_name="修改时间",auto_now_add=True)
    display=models.BooleanField(verbose_name="商品是否被删除",)
    uid=models.IntegerField(verbose_name="用户id",)
    sid=models.IntegerField(verbose_name="商品id",)
    quantity=models.IntegerField(verbose_name="商品数量",)
    class Meta:
         verbose_name = "用户购物车"
         verbose_name_plural = "用户购物车"

demo/APP1/forms.py
from django import forms

    

    


class UserForm_add(forms.Form):
    adduser=forms.CharField(label="",max_length=128,widget=forms.TextInput(attrs={"placeholder":"用户名"}))
    addpwd=forms.CharField(label="",max_length=256,widget=forms.PasswordInput(attrs={"placeholder":"密码"}))
class UserForm_login(forms.Form):
    loginuser=forms.CharField(label="",max_length=128,widget=forms.TextInput(attrs={"placeholder":"用户名"}))
    loginpwd=forms.CharField(label="",max_length=256,widget=forms.PasswordInput(attrs={"placeholder":"密码"}))






class imgtest(forms.Form):

    img=forms.ImageField(label="img")
class goods(forms.Form):
        sort={
             (1,"电器"),
             (2,"书籍"),
        }
        Goods_name=forms.CharField(label="商品名",max_length=128)
        Goods_level=forms.IntegerField(label="成色")
        Goods_remark=forms.CharField(label="商品描述",max_length=255)
        Goods_price=forms.DecimalField(label="商品价钱",decimal_places=3)
        Goods_sort=forms.ChoiceField (label="商品类别",choices=sort)
        Goods_coumt=forms.IntegerField(label="数量")
        Goods_img=forms.ImageField(label="img")
class userinfo(forms.Form):    
# def __init__(self,*args, **kwargs):
#     super().__init__(*args, **kwargs)
    sort={
            ("male","男"),
            ("female","女"),
            ("未知","保密")
        }

    sex=forms.ChoiceField(label="性别",choices=sort)
    email=forms.EmailField(label="Email")
    message=forms.CharField(label="",max_length=255) 
    img=forms.ImageField(label="img")

demo/APP1/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.http import JsonResponse
from .mypy import login_my
from .mypy import img_test
from .mypy import user_info
from . import forms

from . import models
import os
import pyqrcode
import random
# Create your views here.

def frame(func): 
    def f(request,num=1):
        if request.session.get("info",None):
            session=request.session
            info=session.get("info")
            img=models.User.objects.get(id=session.get("info")["id"]).avater
        else :
            img="/img/my.jpg"
        return func(request,img,num)
    return f



#主页
@frame
def index(request,*args):
    if  request.method=="GET":
        if args[1]<=0:

            return redirect("/index")
        # data=models.Goods.objects.order_by("?")[(args[1]-1)*15:(args[1]-1)*15+15]
        user=models.User.objects.all()
        data=list(models.Goods.objects.all()[(args[1]-1)*15:(args[1]-1)*15+15])
        random.shuffle(data)
        count=range(models.Goods.objects.count()//15+1)
        print(locals())
        return render(request,"index/index.html",locals())
    print(request.POST)
    return redirect("/index")

#登录、注册
def login(request):
    if request.method=="POST":
    #    print(request.POST)
       return login_my.post(request)
    return login_my.get(request)


#个人界面
@frame
def user_page(request,*args):
    if request.session.get("info",None):
        if request.method=="GET":
            return user_info.get(request,*args)
        
        return user_info.post(request,*args)
    else:
        return redirect("login/")
#个人商品界面---------（合并到个人界面）
def user_goods_page(request):
    pass



#上架商品
@frame
def submit(request,*args):
    print(request)
    goods=forms.goods()
    if request.method=="GET":
        if request.session.get("info",None):
            return render(request,"submit/submit.html",locals())
        else:
            return redirect("/login")
    data=forms.goods(request.POST,request.FILES)

    
    if data.is_valid():
        req=data.cleaned_data
        img=req.get("Goods_img")
        img_path=os.path.join("APP1","static","img",img.name)
        with open(img_path,"wb+") as f:
            for chunk in img.chunks():
                f.write(chunk)
        print(req)
        models.Goods.objects.create(name=req.get("Goods_name"),
                                    level=req.get("Goods_level"),
                                    remark=req.get("Goods_remark"),
                                    price=req.get("Goods_price"),
                                    sort=req.get("Goods_sort"),
                                    count=req.get("Goods_coumt"),
                                    image=os.path.join("img",img.name),
                                    uid=request.session.get("info").get("id")
                                    )
    return redirect("/user")

#购物车页面
@frame
def cart(request,*args):
    if request.session.get("info",None):
        if request.method=="GET":
            cart=models.Shopping_cart.objects.filter(uid=request.session.get("info")["id"])
            data=[]
            suser=[]
            for i in cart:
                goods=models.Goods.objects.get(id=i.sid)
                data.append({
                    "id":goods.id,
                    "name":goods.name,
                    "price":goods.price,
                    "img":goods.image,
                    "count":goods.count,    
                    "display":goods.display,
                    "seller_id":goods.uid
                    })
                scr={
                    "seller_id":goods.uid,
                    "uname":models.User.objects.get(id=goods.uid).name,
                    "avater":models.User.objects.get(id=goods.uid).avater,
                }
                if scr not in suser :
                    suser.append(scr) 
        
            print(data)
            return render(request,"cart/cart.html",locals())
        print(request.POST)
        models.Shopping_cart.objects.create(
            display=True,
            uid=request.session.get("info")["id"],
            sid=request.POST.get("Goods"),
            quantity=1
        )
        return redirect("/cart")
    else:
            return redirect("/login")
#搜索展示
def searching_goods(request):
    pass
@frame
def wallet(request,*args):
    if request.session.get("info",None):
        return render(request,"wallet/wallet.html",locals())
    return redirect("/login")
def exit(req):
    req.session.flush()
    return redirect("/index")

def user_set(request):
    set=models.Goods.objects.filter(id=request.POST.get("Goods"))
    set.update(display=not set[0].display)
    return redirect("/user")

def show(request,uid):
    user=models.User.objects.get(id=uid)
    data=models.Goods.objects.filter(uid=uid)
    args=(user.avater,)
    print(locals())
    return render(request,"user/other.html",locals())
def test(request,i):
    data=models.Shopping_cart.objects.filter(uid=request.session.get("info")["id"])
    if i==0:
        data.first().delete()
    elif i==1:
        data.delete()
    return redirect("/cart")
@frame
def qr(req,*args):
    if req.session.get("info",None):
        url=req.get_host()+"/user/"+str(req.session.get("info")["id"])
        url=pyqrcode.create(url,version=5)
        qr_path=os.path.join("APP1","static","qr",str(req.session.get("info")["id"])+".svg")
        print(url.terminal(quiet_zone=1))
  
        url.svg(qr_path,scale=8)
        qr=os.path.join("qr",str(req.session.get("info")["id"])+".svg")
        print(locals())
        return render(req,"QR/qr.html",locals())
    return redirect("/login")
def img(req,str):
    return redirect("/static/img/"+str)
@frame
def set(req,*args):

    if req.method=="GET":
        uid=req.session.get("info").get("id")
        user=models.User.objects.get(id=uid)
        data=models.Goods.objects.filter(uid=uid)
        form_data = {
        "sex":user.sex,
        "email": user.email,
        "message":  user.message if user.message else "说点什么吧...",
        "img":user.avater
        }
        formuser=forms.userinfo(form_data)
        print(locals())
        return render(req,"set_user/set_user.html",locals())
    data=forms.userinfo(req.POST,req.FILES)
    print(data.changed_data)
    if data.is_valid():
        user=models.User.objects.filter(id=req.session.get("info").get("id"))
        if data.cleaned_data.get("message")!="说点什么吧...":
            user.update(message=data.cleaned_data.get("message"))
        if data.cleaned_data.get("email")!=user.values()[0].get("email"):
            user.update(email=data.cleaned_data.get("email"))
        if data.cleaned_data.get("sex")!=user.values()[0].get("sex"):
            user.update(sex=data.cleaned_data.get("sex")) 
        print(data.cleaned_data)
        if data.cleaned_data.get("img")!=user.values()[0].get("img"):
            req=data.cleaned_data
            img=req.get("img")
            img_path=os.path.join("APP1","static","img",img.name)
            with open(img_path,"wb+") as f:
                for chunk in img.chunks():
                    f.write(chunk)
            user.update(avater=os.path.join("img",img.name))
    
    return redirect("/user")

def docs(request):
    return render(request, 'help/help_user.html')

demo/APP1/templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ tag }}</title>
    <!-- 导入字体图标 -->
    <link rel="stylesheet" href="{% static 'login/iconfont.css'%}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.4.1/css/bootstrap.css' %}">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            /* 字体无法选中 */
            user-select: none;
        }

        body {
            width: 100%;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 12px;
            background-color: #ecf0f3;
            color: #a0a5a8;
        }

        .shell {
            position: relative;
            width: 1000px;
            min-width: 1000px;
            min-height: 600px;
            height: 600px;
            padding: 25px;
            background-color: #ecf0f3;
            box-shadow: 10px 10px 10px #d1d9e6, -10px -10px 10px #f9f9f9;
            border-radius: 12px;
            overflow: hidden;
        }

        /* 设置响应式 */
        @media (max-width: 1200px) {
            .shell {
                transform: scale(0.7);
            }
        }

        @media (max-width: 1000px) {
            .shell {
                transform: scale(0.6);
            }
        }

        @media (max-width: 800px) {
            .shell {
                transform: scale(0.5);
            }
        }

        @media (max-width: 600px) {
            .shell {
                transform: scale(0.4);
            }
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            position: absolute;
            top: 0;
            width: 600px;
            height: 100%;
            padding: 25px;
            background-color: #ecf0f3;
            transition: 1.25s;
        }

        .form {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            width: 100%;
            height: 100%;
        }

        .iconfont {
            margin: 0 5px;
            border: rgba(0, 0, 0, 0.5) 2px solid;
            border-radius: 50%;
            font-size: 25px;
            padding: 3px;
            opacity: 0.5;
            transition: 0.1s;
        }

        .iconfont:hover {
            opacity: 1;
            transition: 0.15s;
            cursor: pointer;
        }

        .form_input {
            width: 350px;
            height: 40px;
            margin: 4px 0;
            padding-left: 25px;
            font-size: 13px;
            letter-spacing: 0.15px;
            border: none;
            outline: none;
            background-color: #ecf0f3;
            transition: 0.25s ease;
            border-radius: 8px;
            box-shadow: inset 2px 2px 4px #d1d9e6, inset -2px -2px 4px #f9f9f9;
        }

        .form_input:focus {
            box-shadow: inset 4px 4px 4px #d1d9e6, inset -4px -4px 4px #f9f9f9;
        }

        .form_span {
            margin-top: 30px;
            margin-bottom: 12px;
        }

        .form_link {
            color: #181818;
            font-size: 15px;
            margin-top: 25px;
            border-bottom: 1px solid #a0a5a8;
            line-height: 2;
        }

        .title {
            font-size: 34px;
            font-weight: 700;
            line-height: 3;
            color: #181818;
            letter-spacing: 10px;
        }

        .description {
            font-size: 14px;
            letter-spacing: 0.25px;
            text-align: center;
            line-height: 1.6;
        }

        .button {
            width: 180px;
            height: 50px;
            border-radius: 25px;
            margin-top: 50px;
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1.15px;
            background-color: #4B70E2;
            color: #f9f9f9;
            box-shadow: 8px 8px 16px #d1d9e6, -8px -8px 16px #f9f9f9;
            border: none;
            outline: none;
        }

        .a-container {
            z-index: 100;
            left: calc(100% - 600px);
        }

        .b-container {
            left: calc(100% - 600px);
            z-index: 0;
        }

        .switch {
            display: flex;
            justify-content: center;
            align-items: center;
            position: absolute;
            top: 0;
            left: 0;
            height: 100%;
            width: 400px;
            padding: 50px;
            z-index: 200;
            transition: 1.25s;
            background-color: #ecf0f3;
            overflow: hidden;
            box-shadow: 4px 4px 10px #d1d9e6, -4px -4px 10px #d1d9e6;
        }

        .switch_circle {
            position: absolute;
            width: 500px;
            height: 500px;
            border-radius: 50%;
            background-color: #ecf0f3;
            box-shadow: inset 8px 8px 12px #b8bec7, inset -8px -8px 12px #fff;
            bottom: -60%;
            left: -60%;
            transition: 1.25s;
        }

        .switch_circle-t {
            top: -30%;
            left: 60%;
            width: 300px;
            height: 300px;
        }

        .switch_container {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            position: absolute;
            width: 400px;
            padding: 50px 55px;
            transition: 1.25s;
        }

        .switch_button {
            cursor: pointer;
        }

        .switch_button:hover,
        .submit:hover {
            box-shadow: 6px 6px 10px #d1d9e6, -6px -6px 10px #f9f9f9;
            transform: scale(0.985);
            transition: 0.25s;
        }

        .switch_button:active,
        .switch_button:focus {
            box-shadow: 2px 2px 6px #d1d9e6, -2px -2px 6px #f9f9f9;
            transform: scale(0.97);
            transition: 0.25s;
        }

        .is-txr {
            left: calc(100% - 400px);
            transition: 1.25s;
            transform-origin: left;
        }

        .is-txl {
            left: 0;
            transition: 1.25s;
            transform-origin: right;
        }

        .is-z {
            z-index: 200;
            transition: 1.25s;
        }

        .is-hidden {
            visibility: hidden;
            opacity: 0;
            position: absolute;
            transition: 1.25s;
        }

        .is-gx {
            animation: is-gx 1.25s;
        }

        @keyframes is-gx {

            0%,
            10%,
            100% {
                width: 400px;
            }

            30%,
            50% {
                width: 500px;
            }
        }
    </style>
</head>
<body>

    <div class="shell">
        <div class="container a-container" id="a-container">
            <div class="form" id="a-form">
            <!-- <form action="/login/" method="post" class="form" id="a-form"> -->
                <h2 class="form_title title">创建账号</h2>
                <div class="form_icons">
                    <i class="iconfont icon-QQ"></i>
                    <i class="iconfont icon-weixin"></i>
                    <i class="iconfont icon-bilibili-line"></i>
                </div>
                <span class="form_span">选择注册方式或电子邮箱注册</span>
                {{ login_form_add }}
                <button class="button" form="a-form" id="login">注册</button>
            <!-- </form> -->
            </div>
        </div>

        <div class="container b-container" id="b-container">
            <!-- <form accept="/login" method="post" class="form" id="b-form"> -->
                <div class="form" id="b-form">
                <h2 class="form_title title">登入账号</h2>
                <div class="form_icons">
                    <i class="iconfont icon-QQ"></i>
                    <i class="iconfont icon-weixin"></i>
                    <i class="iconfont icon-bilibili-line"></i>
                </div>
                <span class="form_span">选择登录方式或电子邮箱登录</span>
                {{ login_form_login }}
                <a class="form_link">忘记密码？</a>
                <button class="button" type="submit" id="register">登录</button>
            </div>
            <!-- </form> -->
        </div>

        <div class="switch" id="switch-cnt">
            <div class="switch_circle"></div>
            <div class="switch_circle switch_circle-t"></div>
            <div class="switch_container" id="switch-c1">
                <h2 class="switch_title title" style="letter-spacing: 0;">Welcome Back！</h2>
                <p class="switch_description description">已经有账号了嘛，去登录账号来进入奇妙世界吧！！！</p>
                <button class="switch_button button switch-btn">登录</button>
            </div>

            <div class="switch_container is-hidden" id="switch-c2">
                <h2 class="switch_title title" style="letter-spacing: 0;">Hello Friend！</h2>
                <p class="switch_description description">去注册一个账号，成为尊贵的粉丝会员，让我们踏入奇妙的旅途！</p>
                <button class="switch_button button switch-btn">注册</button>
            </div>
        </div>
    </div>
</body>

<script src="{% static 'jquery-3.6.4.min.js' %}"></script>
<script src="{% static 'bootstrap-3.4.1\js\bootstrap.js' %}"></script>
<script>
    let switchCtn = document.querySelector("#switch-cnt");
    let switchC1 = document.querySelector("#switch-c1");
    let switchC2 = document.querySelector("#switch-c2");
    let switchCircle = document.querySelectorAll(".switch_circle");
    let switchBtn = document.querySelectorAll(".switch-btn");
    let aContainer = document.querySelector("#a-container");
    let bContainer = document.querySelector("#b-container");
    let allButtons = document.querySelectorAll(".submit");

    let getButtons = (e) => e.preventDefault()
    let changeForm = (e) => {
        // 修改类名
        switchCtn.classList.add("is-gx");
        setTimeout(function () {
            switchCtn.classList.remove("is-gx");
        }, 1500)
        switchCtn.classList.toggle("is-txr");
        switchCircle[0].classList.toggle("is-txr");
        switchCircle[1].classList.toggle("is-txr");

        switchC1.classList.toggle("is-hidden");
        switchC2.classList.toggle("is-hidden");
        aContainer.classList.toggle("is-txl");
        bContainer.classList.toggle("is-txl");
        bContainer.classList.toggle("is-z");
    }
    // 点击切换
    let shell = (e) => {
        for (var i = 0; i < allButtons.length; i++)
            allButtons[i].addEventListener("click", getButtons);
        for (var i = 0; i < switchBtn.length; i++)
            switchBtn[i].addEventListener("click", changeForm)
    }
    window.addEventListener("load", shell);
    
    $(document).ready(function(){
        $("#login").click(function(){
        $.ajax({
            url: '/login/',
            method: 'POST',
            data:{"adduser":$("#id_adduser").val(),
                "addpwd":$('#id_addpwd').val()
                },
            headers:{"X-CSRFToken":" {{ csrf_token }}"},
            success: function(req) {
            alert(req.sign+" 点击“确定”跳转");
            window.location="/index";
            }
        })
        });
        $("#register").click(function(){
        $.ajax({
            url: '/login/',
            method: 'POST',
            data:{"loginuser":$("#id_loginuser").val(),
                "loginpwd":$('#id_loginpwd').val()
                },
            headers:{"X-CSRFToken":" {{ csrf_token }}"},
            success: function(req) {
                if(req.sign==='ok'){
                window.location="/index";
             }
             else if(req.sign==="pwderror")
             {
                alert("密码或账号有误请重新输入！")
             }
             else if(req.sign==="nameerror")
             {
                alert("用户不存在，请注册！")
             }
            }
        })
        });
    });
</script>

</body>

</html>